pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                sh 'sudo cp java-tomcat-sample/target/*.war  /opt/tomcat/webapps'
                echo "Deploy Application To Staging Environment"
                 }
        }
    }
}
